name: Update myself

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 12 1 * *'
    - cron: '0 12 13 12 *'
  workflow_dispatch:

jobs:
  create_version_tag:
    runs-on: ubuntu-latest
    name: Create version tag
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Version action step
        uses: ./ # Uses an action in the root directory
        id: version
      # Use the output from the `hello` step
      - name: Get the output version
        run: |
          echo "The version is ${{ steps.version.outputs.version }}"
          echo "The tag is ${{ steps.version.outputs.tag }}"
      - run: git config --global user.name github-actions[bot]
      - run: git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: npm version --allow-same-version ${{ steps.version.outputs.version }}
      - run: git pull
      - run: git push
      - name: Create Release
        if: steps.create_tag.outputs.successful
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.version.outputs.tag }}
          tag: ${{ steps.version.outputs.tag }}
          body: "# Congrats, you're @ ${{ steps.version.outputs.tag }}"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
